In [1]:
import numpy as np # NumPy import
from bokeh.palettes import Set3_10

# Creation of list and creation of an array based on the list
python_list = [1, 2, 3]
numpy_array = np.array(python_list)
numpy_array

array([1, 2, 3])

In [2]:
numbers_zero_to_nine = np.arange(0, 10)
numbers_zero_to_nine

numbers_step_2 = np.arange(0, 11, 2)
numbers_step_2

numbers_random1 = np.random.rand(10)
numbers_random1

numbers_random2 = np.random.rand(10) * 10
numbers_random2

array([2.74944214e+00, 6.35775423e+00, 4.21666632e+00, 2.26299170e+00,
       9.97004581e+00, 3.97395860e+00, 2.33437536e+00, 2.80105242e+00,
       8.27654871e+00, 1.62489439e-03])

In [3]:
one_to_hundred = np.random.randint(0, 100, 10)
one_to_hundred
one_to_hundred.max()
one_to_hundred.argmax()
one_to_hundred.min()
one_to_hundred.argmin()
one_to_hundred[3]
one_to_hundred[2:5]

array([54, 35, 53])

In [4]:
import pandas as pd

labels = ['a', 'b', 'c']
values1 = [7, 8, 9]
my_dict = {'a': 10, 'b': 11, 'c': 12, 'd': 13}

In [5]:
set1 = pd.Series(data=values1, index=labels)
set1

a    7
b    8
c    9
dtype: int64

In [6]:
set2 = pd.Series(my_dict)
set2

a    10
b    11
c    12
d    13
dtype: int64

In [7]:
set3 = set1 + set2
set3

a    17.0
b    19.0
c    21.0
d     NaN
dtype: float64

In [8]:
import pandas as pd
import numpy as np

list1 = np.random.randint(1, 21, 4)
list2 = np.random.randint(1, 21, 4)
list3 = np.random.randint(1, 21, 4)

labels = ['a', 'b', 'c']
cols = ['W', 'X', 'Y', 'Z']

dataArray = np.array([list1, list2, list3])
dataFrame = pd.DataFrame(data=dataArray, index=labels, columns=cols)
dataFrame

W   X   Y   Z
a   8  12   8  20
b  13   9  15   8
c   2  15  19   3

In [9]:
dataFrame['X']
dataFrame[['X', 'Y']]
dataFrame.Z
dataFrame.insert(4, 'Sum(X+Y)', dataFrame.X + dataFrame.Y, True)
dataFrame

W   X   Y   Z  Sum(X+Y)
a   8  12   8  20        20
b  13   9  15   8        24
c   2  15  19   3        34

In [10]:
dataFrame.drop('Sum(X+Y)', axis=1, inplace=True)
dataFrame

W   X   Y   Z
a   8  12   8  20
b  13   9  15   8
c   2  15  19   3

In [11]:
newRow = pd.DataFrame(data={1: 'W', 2: 'X', 3: 'Y', 4: 'Z'}, index=['d'])
newRow

dataFrame = pd.concat([dataFrame, newRow])
dataFrame

W     X     Y     Z    1    2    3    4
a   8.0  12.0   8.0  20.0  NaN  NaN  NaN  NaN
b  13.0   9.0  15.0   8.0  NaN  NaN  NaN  NaN
c   2.0  15.0  19.0   3.0  NaN  NaN  NaN  NaN
d   NaN   NaN   NaN   NaN    W    X    Y    Z

In [36]:
titanicDf = pd.read_csv('data/Titanic-Dataset.csv')
titanicDf
# titanicDf.head(20)
# titanicDf.tail()
titanicDf.info()
# titanicDf.sample()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [29]:
titanicDf.drop('Cabin', axis=1, inplace=True)
titanicDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [38]:
l1 = titanicDf[titanicDf['Age'].isnull()].index
titanicDf.info()
titanicDf.drop(l1, axis=0, inplace=True)
titanicDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  714 non-null    int64  
 1   Survived     

In [41]:
dsSalaries = pd.read_csv('data/ds_salaries.csv')
dsSalaries.head(5)

work_year experience_level employment_type                 job_title  \
0       2023               SE              FT  Principal Data Scientist   
1       2023               MI              CT               ML Engineer   
2       2023               MI              CT               ML Engineer   
3       2023               SE              FT            Data Scientist   
4       2023               SE              FT            Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   80000             EUR          85847                 ES           100   
1   30000             USD          30000                 US           100   
2   25500             USD          25500                 US           100   
3  175000             USD         175000                 CA           100   
4  120000             USD         120000                 CA           100   

  company_location company_size  
0               ES            L  
1               US            S  
2               US            S  
3               CA            M  
4               CA            M

In [42]:
dsSalaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   work_year           3755 non-null   int64 
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64 
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64 
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64 
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB
